//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceReferenceDepartamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Departamento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Area))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDepartamento.IServicioDepartamento")]
    public interface IServicioDepartamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Saludar", ReplyAction="http://tempuri.org/IServicioDepartamento/SaludarResponse")]
        string Saludar(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Saludar", ReplyAction="http://tempuri.org/IServicioDepartamento/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Add", ReplyAction="http://tempuri.org/IServicioDepartamento/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceReferenceDepartamento.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        PL_MVC.ServiceReferenceDepartamento.Result Add(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Add", ReplyAction="http://tempuri.org/IServicioDepartamento/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> AddAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Update", ReplyAction="http://tempuri.org/IServicioDepartamento/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceReferenceDepartamento.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Area))]
        PL_MVC.ServiceReferenceDepartamento.Result Update(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Update", ReplyAction="http://tempuri.org/IServicioDepartamento/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> UpdateAsync(ML.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Delete", ReplyAction="http://tempuri.org/IServicioDepartamento/DeleteResponse")]
        PL_MVC.ServiceReferenceDepartamento.Result Delete(int IdDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/Delete", ReplyAction="http://tempuri.org/IServicioDepartamento/DeleteResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> DeleteAsync(int IdDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/GetAll", ReplyAction="http://tempuri.org/IServicioDepartamento/GetAllResponse")]
        PL_MVC.ServiceReferenceDepartamento.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/GetAll", ReplyAction="http://tempuri.org/IServicioDepartamento/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/GetById", ReplyAction="http://tempuri.org/IServicioDepartamento/GetByIdResponse")]
        PL_MVC.ServiceReferenceDepartamento.Result GetById(int IdDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDepartamento/GetById", ReplyAction="http://tempuri.org/IServicioDepartamento/GetByIdResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> GetByIdAsync(int IdDepartamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDepartamentoChannel : PL_MVC.ServiceReferenceDepartamento.IServicioDepartamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDepartamentoClient : System.ServiceModel.ClientBase<PL_MVC.ServiceReferenceDepartamento.IServicioDepartamento>, PL_MVC.ServiceReferenceDepartamento.IServicioDepartamento {
        
        public ServicioDepartamentoClient() {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Saludar(string Nombre) {
            return base.Channel.Saludar(Nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string Nombre) {
            return base.Channel.SaludarAsync(Nombre);
        }
        
        public PL_MVC.ServiceReferenceDepartamento.Result Add(ML.Departamento departamento) {
            return base.Channel.Add(departamento);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> AddAsync(ML.Departamento departamento) {
            return base.Channel.AddAsync(departamento);
        }
        
        public PL_MVC.ServiceReferenceDepartamento.Result Update(ML.Departamento departamento) {
            return base.Channel.Update(departamento);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> UpdateAsync(ML.Departamento departamento) {
            return base.Channel.UpdateAsync(departamento);
        }
        
        public PL_MVC.ServiceReferenceDepartamento.Result Delete(int IdDepartamento) {
            return base.Channel.Delete(IdDepartamento);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> DeleteAsync(int IdDepartamento) {
            return base.Channel.DeleteAsync(IdDepartamento);
        }
        
        public PL_MVC.ServiceReferenceDepartamento.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL_MVC.ServiceReferenceDepartamento.Result GetById(int IdDepartamento) {
            return base.Channel.GetById(IdDepartamento);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceDepartamento.Result> GetByIdAsync(int IdDepartamento) {
            return base.Channel.GetByIdAsync(IdDepartamento);
        }
    }
}
